trigger:
- master

stages:
- stage: 'teststage'
  jobs:
  - job: 'testjob'
    pool:
      default
    steps:
    - bash: |
        cd ~
        sudo docker run --rm -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py -t  http://10.175.10.177/FYP_Website/codes/   -r fypreport.html -m 15
      displayName: 'OWASP ZAP Scan'