trigger:
- master

stages:
- stage: 'buildstage'
  jobs:
  - job: 'buildjob'
    pool:
      default
    steps:
    - bash: |
        cd ~
        sudo docker run --rm exakat/exakat:latest
        sudo docker run --rm  exakat/exakat:latest project -p fyp4 -R https://github.com/zheng-hui/vWebsite.git --format Text
        sudo docker run --rm  -v `pwd`/projects:/usr/src/exakat/projects/ exakat/exakat:latest project -p fyp4 -R https://github.com/zheng-hui/vWebsite.git
      displayName: 'Exacat Scan'