trigger:
- master

stages:
- stage: 'buildstage'
  jobs:
  - job: 'buildjob'
    pool:
      default
    steps:
    - bash: |
        cd ~
        sudo docker run --rm -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py -t  http://10.175.10.177/FYP_Website/codes/   -r fypreport_plswork.html -m 15
      displayName: 'OWASP ZAP Scan'

    - bash: |
        cd ~
        python2 staticDomXSS_scanner.py -d ~/Static-DOM-XSS-Scanner/FYP_DOM/
      displayName:  'DOM XSS Scan'