trigger:
- master

stages:
- stage: 'buildstage'
  jobs:
  - job: 'buildjob'
    pool:
      default
    steps:
    - bash: |
        cd ~
        sudo docker run --rm exakat/exakat:latest
        sudo docker run --rm  exakat/exakat:latest project -p fyp4 -R https://github.com/zheng-hui/vWebsite.git --format Text
        sudo docker run --rm  -v `pwd`/projects:/usr/src/exakat/projects/ exakat/exakat:latest project -p fyp4 -R https://github.com/zheng-hui/vWebsite.git
      displayName: 'Exacat Scan'
      
    - bash: |
        cd ~
        cd Static-DOM-XSS-Scanner
        python2 staticDomXSS_scanner.py -d ~/Static-DOM-XSS-Scanner/FYP_DOM/
      continueOnError: true
      displayName:  'DOM XSS Scan'
    
    - bash: |
        cd ~
        ./xss_s_school.sh |  grep  '<script>alert(document.cookie)</script>' > stored_result.txt
      continueOnError: true
      displayName:  'Stored XSS Scan'
    
    - bash: |
        cd ~
        ./xss_r_school.sh | grep '<script>alert(123)</script>' > reflected_result.txt
      continueOnError: true
      displayName:  'Reflected XSS Scan'
      
    - bash: |
        cd ~
        ./sql_injection_school.sh | grep 'Welcome' > sqlinjection_result.txt
      continueOnError: true
      displayName:  'SQL Injection Scan'